### ISSUE TITLE
js文件没起作用啊？

### ISSUE THREAD

**Issue by wang2650** [bing-framework/Bing.Extensions.Swashbuckle#1]
你的测试项目里，swagger也没汉化啊。  
弹出的输出token窗口也没汉化。
导出文件按钮也没有。

**Comment by jianxuanbing** [comment]
导出文件按钮，这个要注入js
![image](https://user-images.githubusercontent.com/7100363/54876222-33c98480-4e47-11e9-907c-a6d8a282ef24.png)
然而，汉化得改动底层UI才能实现，所以汉化只能延后了
