### ISSUE TITLE
汪总，nuget包建议做个.nuspec 文件文件 把Microsoft.AspNetCore.Mvc.Versioning依赖加进去

### ISSUE THREAD

**Issue by kiler398** [bing-framework/Bing.Extensions.Swashbuckle#2]

**Comment by kiler398** [comment]
现在。net core默认项目打开  app.UseApiVersioning(); 报错过不去 是没有引用 Microsoft.AspNetCore.Mvc.Versioning，建议你的包带上

**Comment by jianxuanbing** [comment]
`UseApiVersioning` 可以不用的，只有在接口上打上`[ApiVersion()]` 才需要用到的，这个属于可用可不用功能
